var repos=[{id:'all',name:'All Projects'},{id:'otto',name:'Otto',badge:'rb-otto'},{id:'circle',name:'Circle',badge:'rb-circle'},{id:'OliveWolf',name:'OliveWolf',badge:'rb-olivewolf'},{id:'miraphant',name:'Miraphant',badge:'rb-miraphant'},{id:'EasyHermes',name:'EasyHermes',badge:'rb-easyhermes'}];
var curRepo='all';
var DB={get:function(k,d){try{var v=localStorage.getItem('fu-'+k);return v?JSON.parse(v):d}catch(e){return d}},set:function(k,v){localStorage.setItem('fu-'+k,JSON.stringify(v))}};
function seed(){if(!DB.get('updates'))DB.set('updates',[
{id:'F001',repo:'otto',title:'Mem0 structured memory integration',status:'done',owner:'krx521920',date:'2026-07-06',next:'Monitor memory retrieval accuracy',note:'Mem0 + LangGraph task orchestration deployed. OR-Tools optimization active.'},
{id:'F002',repo:'otto',title:'Feishu project collaboration',status:'on',owner:'NSIETeam',date:'2026-07-06',next:'Ship project collaboration planner v2',note:'Extended feishu actions + planner framework added.'},
{id:'F003',repo:'otto',title:'Codebase memory MCP adapter',status:'on',owner:'NSIETeam',date:'2026-07-06',next:'Wire MCP tools to project memory manager',note:'CLI project memory commands + org memory MVP in progress.'},
{id:'F004',repo:'miraphant',title:'Website OA system integration',status:'on',owner:'NSIETeam',date:'2026-07-07',next:'Deploy to GitHub Pages + test auth flow',note:'OA, follow-up, and contribution log merged into employee portal with password auth.'},
{id:'F005',repo:'OliveWolf',title:'Real-time audio-driven conversation',status:'plan',owner:'Felix201209',date:'2026-07-04',next:'Benchmark latency on enterprise GPU',note:'Dual render backends working. Need enterprise deployment testing.'},
{id:'F006',repo:'circle',name:'Circle',title:'AI-driven property matching engine',status:'on',owner:'NSIETeam',date:'2026-07-03',next:'Onboard first 3 enterprise clients',note:'Matching algorithm v2 deployed. B2B platform ready for pilot.'},
{id:'F007',repo:'EasyHermes',title:'Core pipeline optimization',status:'hold',owner:'krx521920',date:'2026-07-02',next:'Resume after Otto v1.4 release',note:'On hold pending Otto memory module completion.'}
])}
function sBg(s){var m={on:'bg-on',hold:'bg-hold',done:'bg-done',risk:'bg-risk',plan:'bg-plan'};var l={on:'Active',hold:'On Hold',done:'Done',risk:'At Risk',plan:'Planned'};return'<span class="bg '+(m[s]||'bg-plan')+'">'+l[s]+'</span>'}
function repoBadge(r){var rd=repos.find(function(x){return x.id===r});if(!rd||!rd.badge)return r;return'<span class="repo-badge '+rd.badge+'">'+rd.name+'</span>'}
function toast(m){var e=document.getElementById('toast');if(!e){e=document.createElement('div');e.id='toast';e.className='toast';document.body.appendChild(e)}e.textContent=m;e.classList.add('show');setTimeout(function(){e.classList.remove('show')},2500)}
function openM(h){var o=document.getElementById('mo');if(!o){o=document.createElement('div');o.id='mo';o.className='mo';document.body.appendChild(o);o.addEventListener('click',function(e){if(e.target===o)o.classList.remove('show')})}o.innerHTML='<div class="mo-box">'+h+'</div>';o.classList.add('show')}
function closeM(){var o=document.getElementById('mo');if(o)o.classList.remove('show')}
function renderTabs(){document.getElementById('repoTabs').innerHTML=repos.map(function(r){return'<button class="repo-tab '+(curRepo===r.id?'active':'')+'" onclick="curRepo=\''+r.id+'\';renderAll()">'+r.name+'</button>'}).join('')}
function renderStats(){var d=DB.get('updates',[]);var s=[{l:'Total',v:d.length},{l:'Active',v:d.filter(function(x){return x.status==='on'}).length},{l:'Done',v:d.filter(function(x){return x.status==='done'}).length},{l:'At Risk',v:d.filter(function(x){return x.status==='risk'}).length},{l:'On Hold',v:d.filter(function(x){return x.status==='hold'}).length}];document.getElementById('fuStats').innerHTML=s.map(function(x){return'<div class="stat-box"><div class="num">'+x.v+'</div><div class="lbl">'+x.l+'</div></div>'}).join('')}
function renderTable(){var d=DB.get('updates',[]);if(curRepo!=='all')d=d.filter(function(x){return x.repo===curRepo});var rd=repos.find(function(x){return x.id===curRepo});document.getElementById('repoTitle').textContent=rd?rd.name:'All Projects';var body=document.getElementById('fuBody');if(d.length===0){body.innerHTML='<tr><td colspan="8"><div class="empty">No updates</div></td></tr>';return}body.innerHTML=d.map(function(r){return'<tr><td class="mono" style="font-size:12px">'+r.id+'</td><td>'+repoBadge(r.repo)+'</td><td style="max-width:180px;font-weight:600">'+r.title+'</td><td>'+sBg(r.status)+'</td><td>'+r.owner+'</td><td>'+r.date+'</td><td style="max-width:160px;overflow:hidden;text-overflow:ellipsis">'+r.next+'</td><td><div style="display:flex;gap:2px"><button class="btn-gh" onclick="editFU(\''+r.id+'\')">Edit</button><button class="btn-gh" onclick="delFU(\''+r.id+'\')">Delete</button></div></td></tr>'}).join('')}
function openFU(id){var r=null;if(id){r=DB.get('updates',[]).find(function(x){return x.id===id})}var repoOpts=repos.filter(function(x){return x.id!=='all'}).map(function(x){return'<option value="'+x.id+'"'+(r&&r.repo===x.id?' selected':'')+'> '+x.name+'</option>'}).join('');openM('<div class="mo-h"><div class="mo-t">'+(r?'Edit Update':'New Update')+'</div><button class="mo-x" onclick="closeM()">&times;</button></div><div class="mo-b"><input type="hidden" id="fu_id" value="'+(r?r.id:'')+'"><div class="fr"><div class="fg"><label class="fl">Project <span class="req">*</span></label><select class="fs" id="fu_repo">'+repoOpts+'</select></div><div class="fg"><label class="fl">Status</label><select class="fs" id="fu_status"><option value="on"'+(r&&r.status==='on'?' selected':'')+'>Active</option><option value="plan"'+(r&&r.status==='plan'?' selected':'')+'>Planned</option><option value="hold"'+(r&&r.status==='hold'?' selected':'')+'>On Hold</option><option value="risk"'+(r&&r.status==='risk'?' selected':'')+'>At Risk</option><option value="done"'+(r&&r.status==='done'?' selected':'')+'>Done</option></select></div></div><div class="fg"><label class="fl">Title <span class="req">*</span></label><input class="fi" id="fu_title" value="'+(r?r.title:'')+'"></div><div class="fr"><div class="fg"><label class="fl">Owner</label><input class="fi" id="fu_owner" value="'+(r?r.owner:'NSIETeam')+'"></div><div class="fg"><label class="fl">Date</label><input class="fi" id="fu_date" type="date" value="'+(r?r.date:new Date().toISOString().slice(0,10))+'"></div></div><div class="fg"><label class="fl">Next Step</label><input class="fi" id="fu_next" value="'+(r?r.next:'')+'"></div><div class="fg"><label class="fl">Notes</label><textarea class="ft" id="fu_note">'+(r?r.note:'')+'</textarea></div></div><div class="mo-f"><button class="btn-s" onclick="closeM()">Cancel</button><button class="btn-p" onclick="saveFU()">Save</button></div>')}
function saveFU(){var id=document.getElementById('fu_id').value;var title=document.getElementById('fu_title').value.trim();if(!title){toast('Title required!');return}var data={repo:document.getElementById('fu_repo').value,status:document.getElementById('fu_status').value,title:title,owner:document.getElementById('fu_owner').value||'NSIETeam',date:document.getElementById('fu_date').value||new Date().toISOString().slice(0,10),next:document.getElementById('fu_next').value||'',note:document.getElementById('fu_note').value||''};var d=DB.get('updates',[]);if(id){var r=d.find(function(x){return x.id===id});if(r){Object.assign(r,data)}}else{var seq=String(d.length+1).padStart(3,'0');data.id='F'+seq;d.unshift(data)}DB.set('updates',d);closeM();renderAll();toast('Saved')}
function editFU(id){openFU(id)}
function delFU(id){var d=DB.get('updates',[]).filter(function(x){return x.id!==id});DB.set('updates',d);renderAll();toast('Deleted')}
function renderAll(){renderTabs();renderStats();renderTable()}
var nav=document.getElementById('nav');window.addEventListener('scroll',function(){nav.classList.toggle('scrolled',window.scrollY>40)},{passive:true});
document.getElementById('navToggle').addEventListener('click',function(){document.getElementById('navLinks').classList.toggle('open')});
document.querySelectorAll('a[href$=".html"]').forEach(function(a){a.addEventListener('click',function(e){var h=a.getAttribute('href');if(h&&!h.startsWith('http')){e.preventDefault();document.body.style.opacity='0';document.body.style.transition='opacity .15s';setTimeout(function(){window.location.href=h},150)}})});
seed();renderAll();
