"use strict";
var i18n={en:{'s.pending':'Pending','s.approved':'Approved','s.total':'My Total','s.amount':'Amount','c.status':'Status','c.type':'Type','c.amount':'Amount','c.applicant':'Applicant','c.date':'Date','c.dept':'Dept','c.reason':'Reason','c.actions':'Actions','c.submit':'Submit','c.cancel':'Cancel','c.approve':'Approve','c.reject':'Reject','c.delete':'Delete','c.view':'View','c.pending':'Pending','c.approved':'Approved','c.rejected':'Rejected','c.processing':'Processing','c.done':'Done','c.all':'All','c.noData':'No data','c.name':'Name','c.role':'Role','c.start':'Start','c.end':'End','c.days':'days','c.dest':'Destination','c.print':'Print','c.back':'Back','r.new':'New Reimbursement','r.cat':'Category','r.inv':'Invoice No.','r.t.travel':'Travel','r.t.meal':'Meal','r.t.office':'Office','r.t.transport':'Transport','r.t.other':'Other','l.new':'New Leave','l.dur':'Duration','l.t.annual':'Annual','l.t.sick':'Sick','l.t.personal':'Personal','l.t.maternity':'Maternity','l.t.other':'Other','t.new':'New Travel','t.purpose':'Purpose','t.transport':'Transport','t.budget':'Budget','t.t.plane':'Flight','t.t.train':'Train','t.t.car':'Self-drive','t.t.other':'Other','b.new':'Make Badge','b.preview':'Preview','b.style':'Style','b.dark':'Dark','b.light':'Light','b.eid':'Employee ID','b.phone':'Phone','b.valid':'Valid Until','b.list':'Badge List'},zh:{'s.pending':'待审批','s.approved':'已批准','s.total':'我的申请','s.amount':'金额','c.status':'状态','c.type':'类型','c.amount':'金额','c.applicant':'申请人','c.date':'日期','c.dept':'部门','c.reason':'事由','c.actions':'操作','c.submit':'提交','c.cancel':'取消','c.approve':'批准','c.reject':'驳回','c.delete':'删除','c.view':'查看','c.pending':'待审批','c.approved':'已批准','c.rejected':'已驳回','c.processing':'制作中','c.done':'已完成','c.all':'全部','c.noData':'暂无数据','c.name':'姓名','c.role':'职位','c.start':'开始','c.end':'结束','c.days':'天','c.dest':'目的地','c.print':'打印','c.back':'返回','r.new':'新建报销','r.cat':'费用类别','r.inv':'发票号','r.t.travel':'差旅费','r.t.meal':'餐饮费','r.t.office':'办公用品','r.t.transport':'交通费','r.t.other':'其他','l.new':'新建请假','l.dur':'时长','l.t.annual':'年假','l.t.sick':'病假','l.t.personal':'事假','l.t.maternity':'产假','l.t.other':'其他','t.new':'新建出差','t.purpose':'出差目的','t.transport':'交通方式','t.budget':'预算','t.t.plane':'飞机','t.t.train':'火车','t.t.car':'自驾','t.t.other':'其他','b.new':'制作工牌','b.preview':'预览','b.style':'风格','b.dark':'深色','b.light':'浅色','b.eid':'工号','b.phone':'电话','b.valid':'有效期至','b.list':'工牌列表'}};
var L=localStorage.getItem('miraphant-lang')||'en';function t(k){return(i18n[L]&&i18n[L][k])||k}
var DB={get:function(k,d){try{var v=localStorage.getItem('oa-'+k);return v?JSON.parse(v):d}catch(e){return d}},set:function(k,v){localStorage.setItem('oa-'+k,JSON.stringify(v))}};
var cu={name:'Chen Xue',dept:'Design',role:'Design Director',id:'MF-004'};
var CM='reimburse';
function seed(){if(!DB.get('reimburse'))DB.set('reimburse',[{id:'R001',applicant:'Chen Xue',dept:'Design',type:'transport',amount:120,invoiceNo:'INV-2026-004',reason:'Commute taxi',date:'2026-07-02',status:'pending'},{id:'R002',applicant:'Chen Xue',dept:'Design',type:'office',amount:380,invoiceNo:'INV-2026-005',reason:'Design software license',date:'2026-07-04',status:'pending'}]);if(!DB.get('leave'))DB.set('leave',[{id:'L001',applicant:'Chen Xue',dept:'Design',type:'annual',startDate:'2026-07-15',endDate:'2026-07-16',days:2,reason:'Family trip',status:'pending'}]);if(!DB.get('travel'))DB.set('travel',[{id:'T001',applicant:'Chen Xue',dept:'Design',destination:'Shanghai',purpose:'Design summit',transport:'train',startDate:'2026-07-20',endDate:'2026-07-22',budget:3000,status:'approved'}]);if(!DB.get('badge'))DB.set('badge',[{id:'B001',name:'Chen Xue',role:'Design Director',dept:'Design',employeeId:'MF-004',phone:'138****1234',validUntil:'2027-12-31',style:'dark',status:'done'}])}
function fmtM(n){return'\u00a5'+Number(n).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}
function sBg(s){var m={pending:'bg-p',approved:'bg-a',rejected:'bg-r',processing:'bg-pr',done:'bg-d'};var k={pending:'c.pending',approved:'c.approved',rejected:'c.rejected',processing:'c.processing',done:'c.done'};return'<span class="bg '+(m[s]||'bg-p')+'">'+t(k[s]||'c.pending')+'</span>'}
function toast(m){var e=document.getElementById('toast');if(!e){e=document.createElement('div');e.id='toast';e.className='toast';document.body.appendChild(e)}e.textContent=m;e.classList.add('show');setTimeout(function(){e.classList.remove('show')},2500)}
function openM(h){var o=document.getElementById('mo');if(!o){o=document.createElement('div');o.id='mo';o.className='mo';document.body.appendChild(o);o.addEventListener('click',function(e){if(e.target===o)o.classList.remove('show')})}o.innerHTML='<div class="mo-box">'+h+'</div>';o.classList.add('show')}
function closeM(){var o=document.getElementById('mo');if(o)o.classList.remove('show')}
/* Filter: only show current user's data */
function myData(key){return DB.get(key,[]).filter(function(x){return x.applicant===cu.name||(key==='badge'&&x.name===cu.name)})}
var rF='all';
function rR(){var d=myData('reimburse');var f=rF==='all'?d:d.filter(function(r){return r.status===rF});var tm={travel:'r.t.travel',meal:'r.t.meal',office:'r.t.office',transport:'r.t.transport',other:'r.t.other'};var ft=['all','pending','approved','rejected'];return'<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:14px;flex-wrap:wrap;gap:10px"><div class="ftabs">'+ft.map(function(x){return'<button class="ftab '+(rF===x?'active':'')+'" onclick="rF=\''+x+'\';rMod()">'+t('c.'+(x==='all'?'all':x))+'</button>'}).join('')+'</div><button class="btn-p btn-sm" onclick="oRM()">+ '+t('r.new')+'</button></div><div class="tw"><div class="ts"><table><thead><tr><th>ID</th><th>'+t('r.cat')+'</th><th>'+t('c.amount')+'</th><th>'+t('r.inv')+'</th><th>'+t('c.reason')+'</th><th>'+t('c.date')+'</th><th>'+t('c.status')+'</th><th>'+t('c.actions')+'</th></tr></thead><tbody>'+(f.length===0?'<tr><td colspan="8"><div class="empty">'+t('c.noData')+'</div></td></tr>':f.map(function(r){return'<tr><td class="mono" style="font-size:12px">'+r.id+'</td><td>'+t(tm[r.type]||'r.t.other')+'</td><td style="font-weight:600">'+fmtM(r.amount)+'</td><td class="mono" style="font-size:12px">'+r.invoiceNo+'</td><td style="max-width:140px;overflow:hidden;text-overflow:ellipsis">'+r.reason+'</td><td>'+r.date+'</td><td>'+sBg(r.status)+'</td><td><div style="display:flex;gap:2px"><button class="btn-gh" onclick="dR(\''+r.id+'\')">'+t('c.delete')+'</button></div></td></tr>'}).join(''))+'</tbody></table></div></div>'}
function oRM(){openM('<div class="mo-h"><div class="mo-t">'+t('r.new')+'</div><button class="mo-x" onclick="closeM()">&times;</button></div><div class="mo-b"><div class="fr"><div class="fg"><label class="fl">'+t('r.cat')+'</label><select class="fs" id="rt"><option value="travel">'+t('r.t.travel')+'</option><option value="meal">'+t('r.t.meal')+'</option><option value="office">'+t('r.t.office')+'</option><option value="transport">'+t('r.t.transport')+'</option><option value="other">'+t('r.t.other')+'</option></select></div><div class="fg"><label class="fl">'+t('c.amount')+' <span class="req">*</span></label><input class="fi" id="ra" type="number" placeholder="0.00" min="0" step="0.01"></div></div><div class="fg"><label class="fl">'+t('r.inv')+'</label><input class="fi" id="ri" placeholder="INV-2026-XXX"></div><div class="fg"><label class="fl">'+t('c.reason')+' <span class="req">*</span></label><textarea class="ft" id="rr"></textarea></div></div><div class="mo-f"><button class="btn-s" onclick="closeM()">'+t('c.cancel')+'</button><button class="btn-p" onclick="sR()">'+t('c.submit')+'</button></div>')}
function sR(){var a=parseFloat(document.getElementById('ra').value),r=document.getElementById('rr').value.trim();if(!a||a<=0){toast('Amount!');return}if(!r){toast('Reason!');return}var d=DB.get('reimburse',[]);var s=String(d.length+1).padStart(3,'0');d.unshift({id:'R'+s,applicant:cu.name,dept:cu.dept,type:document.getElementById('rt').value,amount:a,invoiceNo:document.getElementById('ri').value||'N/A',reason:r,date:new Date().toISOString().slice(0,10),status:'pending'});DB.set('reimburse',d);closeM();rAll();toast('OK')}
function dR(id){var d=DB.get('reimburse',[]).filter(function(x){return x.id!==id});DB.set('reimburse',d);rAll()}
var lF='all';
function rL(){var d=myData('leave');var f=lF==='all'?d:d.filter(function(r){return r.status===lF});var tm={annual:'l.t.annual',sick:'l.t.sick',personal:'l.t.personal',maternity:'l.t.maternity',other:'l.t.other'};var ft=['all','pending','approved','rejected'];return'<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:14px;flex-wrap:wrap;gap:10px"><div class="ftabs">'+ft.map(function(x){return'<button class="ftab '+(lF===x?'active':'')+'" onclick="lF=\''+x+'\';rMod()">'+t('c.'+(x==='all'?'all':x))+'</button>'}).join('')+'</div><button class="btn-p btn-sm" onclick="oLM()">+ '+t('l.new')+'</button></div><div class="tw"><div class="ts"><table><thead><tr><th>ID</th><th>'+t('c.type')+'</th><th>'+t('c.start')+'</th><th>'+t('c.end')+'</th><th>'+t('l.dur')+'</th><th>'+t('c.reason')+'</th><th>'+t('c.status')+'</th><th>'+t('c.actions')+'</th></tr></thead><tbody>'+(f.length===0?'<tr><td colspan="8"><div class="empty">'+t('c.noData')+'</div></td></tr>':f.map(function(r){return'<tr><td class="mono" style="font-size:12px">'+r.id+'</td><td>'+t(tm[r.type]||'l.t.other')+'</td><td>'+r.startDate+'</td><td>'+r.endDate+'</td><td style="font-weight:600">'+r.days+' '+t('c.days')+'</td><td style="max-width:120px;overflow:hidden;text-overflow:ellipsis">'+r.reason+'</td><td>'+sBg(r.status)+'</td><td><div style="display:flex;gap:2px"><button class="btn-gh" onclick="dL(\''+r.id+'\')">'+t('c.delete')+'</button></div></td></tr>'}).join(''))+'</tbody></table></div></div>'}
function oLM(){openM('<div class="mo-h"><div class="mo-t">'+t('l.new')+'</div><button class="mo-x" onclick="closeM()">&times;</button></div><div class="mo-b"><div class="fg"><label class="fl">'+t('c.type')+'</label><select class="fs" id="lt"><option value="annual">'+t('l.t.annual')+'</option><option value="sick">'+t('l.t.sick')+'</option><option value="personal">'+t('l.t.personal')+'</option><option value="maternity">'+t('l.t.maternity')+'</option><option value="other">'+t('l.t.other')+'</option></select></div><div class="fr"><div class="fg"><label class="fl">'+t('c.start')+' <span class="req">*</span></label><input class="fi" id="ls" type="date"></div><div class="fg"><label class="fl">'+t('c.end')+' <span class="req">*</span></label><input class="fi" id="le" type="date" onchange="cL()"></div></div><div class="fg"><label class="fl">'+t('l.dur')+'</label><input class="fi" id="ld" value="0 '+t('c.days')+'" readonly></div><div class="fg"><label class="fl">'+t('c.reason')+' <span class="req">*</span></label><textarea class="ft" id="lr"></textarea></div></div><div class="mo-f"><button class="btn-s" onclick="closeM()">'+t('c.cancel')+'</button><button class="btn-p" onclick="sL()">'+t('c.submit')+'</button></div>')}
function cL(){var s=document.getElementById('ls').value,e=document.getElementById('le').value;if(s&&e){var d=Math.floor((new Date(e)-new Date(s))/86400000)+1;document.getElementById('ld').value=Math.max(0,d)+' '+t('c.days')}}
function sL(){var s=document.getElementById('ls').value,e=document.getElementById('le').value,r=document.getElementById('lr').value.trim();if(!s||!e){toast('Date!');return}if(!r){toast('Reason!');return}var days=Math.max(1,Math.floor((new Date(e)-new Date(s))/86400000)+1);var d=DB.get('leave',[]);var sq=String(d.length+1).padStart(3,'0');d.unshift({id:'L'+sq,applicant:cu.name,dept:cu.dept,type:document.getElementById('lt').value,startDate:s,endDate:e,days:days,reason:r,status:'pending'});DB.set('leave',d);closeM();rAll();toast('OK')}
function dL(id){var d=DB.get('leave',[]).filter(function(x){return x.id!==id});DB.set('leave',d);rAll()}
var tF='all';
function rT(){var d=myData('travel');var f=tF==='all'?d:d.filter(function(r){return r.status===tF});var tm={plane:'t.t.plane',train:'t.t.train',car:'t.t.car',other:'t.t.other'};var ft=['all','pending','approved','rejected'];return'<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:14px;flex-wrap:wrap;gap:10px"><div class="ftabs">'+ft.map(function(x){return'<button class="ftab '+(tF===x?'active':'')+'" onclick="tF=\''+x+'\';rMod()">'+t('c.'+(x==='all'?'all':x))+'</button>'}).join('')+'</div><button class="btn-p btn-sm" onclick="oTM()">+ '+t('t.new')+'</button></div><div class="tw"><div class="ts"><table><thead><tr><th>ID</th><th>'+t('c.dest')+'</th><th>'+t('t.purpose')+'</th><th>'+t('t.transport')+'</th><th>'+t('c.start')+'</th><th>'+t('c.end')+'</th><th>'+t('t.budget')+'</th><th>'+t('c.status')+'</th><th>'+t('c.actions')+'</th></tr></thead><tbody>'+(f.length===0?'<tr><td colspan="9"><div class="empty">'+t('c.noData')+'</div></td></tr>':f.map(function(r){return'<tr><td class="mono" style="font-size:12px">'+r.id+'</td><td style="font-weight:600">'+r.destination+'</td><td style="max-width:120px;overflow:hidden;text-overflow:ellipsis">'+r.purpose+'</td><td>'+t(tm[r.transport]||'t.t.other')+'</td><td>'+r.startDate+'</td><td>'+r.endDate+'</td><td style="font-weight:600">'+fmtM(r.budget)+'</td><td>'+sBg(r.status)+'</td><td><div style="display:flex;gap:2px"><button class="btn-gh" onclick="dT(\''+r.id+'\')">'+t('c.delete')+'</button></div></td></tr>'}).join(''))+'</tbody></table></div></div>'}
function oTM(){openM('<div class="mo-h"><div class="mo-t">'+t('t.new')+'</div><button class="mo-x" onclick="closeM()">&times;</button></div><div class="mo-b"><div class="fg"><label class="fl">'+t('c.dest')+' <span class="req">*</span></label><input class="fi" id="td"></div><div class="fg"><label class="fl">'+t('t.purpose')+' <span class="req">*</span></label><textarea class="ft" id="tp"></textarea></div><div class="fr"><div class="fg"><label class="fl">'+t('t.transport')+'</label><select class="fs" id="tt"><option value="plane">'+t('t.t.plane')+'</option><option value="train">'+t('t.t.train')+'</option><option value="car">'+t('t.t.car')+'</option><option value="other">'+t('t.t.other')+'</option></select></div><div class="fg"><label class="fl">'+t('t.budget')+' <span class="req">*</span></label><input class="fi" id="tb" type="number" placeholder="0" min="0"></div></div><div class="fr"><div class="fg"><label class="fl">'+t('c.start')+' <span class="req">*</span></label><input class="fi" id="ts" type="date"></div><div class="fg"><label class="fl">'+t('c.end')+' <span class="req">*</span></label><input class="fi" id="te" type="date"></div></div></div><div class="mo-f"><button class="btn-s" onclick="closeM()">'+t('c.cancel')+'</button><button class="btn-p" onclick="sT()">'+t('c.submit')+'</button></div>')}
function sT(){var dest=document.getElementById('td').value.trim(),purpose=document.getElementById('tp').value.trim(),budget=parseFloat(document.getElementById('tb').value),start=document.getElementById('ts').value,end=document.getElementById('te').value;if(!dest){toast('Destination!');return}if(!purpose){toast('Purpose!');return}if(!budget||budget<=0){toast('Budget!');return}if(!start||!end){toast('Date!');return}var d=DB.get('travel',[]);var sq=String(d.length+1).padStart(3,'0');d.unshift({id:'T'+sq,applicant:cu.name,dept:cu.dept,destination:dest,purpose:purpose,transport:document.getElementById('tt').value,budget:budget,startDate:start,endDate:end,status:'pending'});DB.set('travel',d);closeM();rAll();toast('OK')}
function dT(id){var d=DB.get('travel',[]).filter(function(x){return x.id!==id});DB.set('travel',d);rAll()}
function rB(){var d=myData('badge');return'<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:14px;flex-wrap:wrap;gap:10px"><h3 style="font-size:15px;font-weight:600">'+t('b.list')+'</h3><button class="btn-p btn-sm" onclick="oBM()">+ '+t('b.new')+'</button></div><div class="tw" style="margin-bottom:28px"><div class="ts"><table><thead><tr><th>ID</th><th>'+t('c.name')+'</th><th>'+t('c.role')+'</th><th>'+t('b.eid')+'</th><th>'+t('b.style')+'</th><th>'+t('c.status')+'</th><th>'+t('c.actions')+'</th></tr></thead><tbody>'+(d.length===0?'<tr><td colspan="7"><div class="empty">'+t('c.noData')+'</div></td></tr>':d.map(function(r){return'<tr><td class="mono" style="font-size:12px">'+r.id+'</td><td style="font-weight:600">'+r.name+'</td><td>'+r.role+'</td><td class="mono" style="font-size:12px">'+r.employeeId+'</td><td>'+(r.style==='dark'?t('b.dark'):t('b.light'))+'</td><td>'+sBg(r.status)+'</td><td><div style="display:flex;gap:2px"><button class="btn-gh" onclick="vB(\''+r.id+'\')">'+t('c.view')+'</button>'+(r.status==='processing'?'<button class="btn-gh" onclick="cB(\''+r.id+'\')">'+t('c.done')+'</button>':'')+'<button class="btn-gh" onclick="dB(\''+r.id+'\')">'+t('c.delete')+'</button></div></td></tr>'}).join(''))+'</tbody></table></div></div><h3 style="font-size:15px;font-weight:600;margin-bottom:16px">'+t('b.preview')+'</h3><div class="ic-prev">'+(d.length===0?'<div class="empty">'+t('c.noData')+'</div>':d.map(function(r){return rIC(r)}).join(''))+'</div>'}
function rIC(r){var dk=r.style==='dark';return'<div class="id-card '+(dk?'dark':'light')+'"><div class="id-card-accent"></div><div class="id-card-body"><div class="id-card-logo">MIRAPHANT</div><div class="id-card-photo">'+r.name.charAt(0)+'</div><div class="id-card-name">'+r.name+'</div><div class="id-card-role">'+r.role+'</div><div class="id-card-info"><div class="id-card-ir"><span class="id-card-il">'+t('b.eid')+'</span><span>'+r.employeeId+'</span></div><div class="id-card-ir"><span class="id-card-il">'+t('c.dept')+'</span><span>'+r.dept+'</span></div><div class="id-card-ir"><span class="id-card-il">'+t('b.phone')+'</span><span>'+r.phone+'</span></div><div class="id-card-ir"><span class="id-card-il">'+t('b.valid')+'</span><span>'+r.validUntil+'</span></div></div></div><div class="id-card-footer">MIRAPHANT / OFFICIAL ID</div></div>'}
function oBM(){openM('<div class="mo-h"><div class="mo-t">'+t('b.new')+'</div><button class="mo-x" onclick="closeM()">&times;</button></div><div class="mo-b"><div class="fr"><div class="fg"><label class="fl">'+t('c.name')+' <span class="req">*</span></label><input class="fi" id="bn" value="'+cu.name+'"></div><div class="fg"><label class="fl">'+t('c.role')+'</label><input class="fi" id="br" value="'+cu.role+'"></div></div><div class="fr"><div class="fg"><label class="fl">'+t('c.dept')+'</label><input class="fi" value="'+cu.dept+'" readonly></div><div class="fg"><label class="fl">'+t('b.eid')+' <span class="req">*</span></label><input class="fi" id="be" value="'+cu.id+'"></div></div><div class="fr"><div class="fg"><label class="fl">'+t('b.phone')+'</label><input class="fi" id="bp" placeholder="138****8888"></div><div class="fg"><label class="fl">'+t('b.valid')+'</label><input class="fi" id="bv" type="date" value="2027-12-31"></div></div><div class="fg"><label class="fl">'+t('b.style')+'</label><div style="display:flex;gap:14px"><label style="display:flex;align-items:center;gap:6px;cursor:pointer"><input type="radio" name="bs" value="dark" checked> '+t('b.dark')+'</label><label style="display:flex;align-items:center;gap:6px;cursor:pointer"><input type="radio" name="bs" value="light"> '+t('b.light')+'</label></div></div><div class="fg"><label class="fl">'+t('b.preview')+'</label><div id="lp" style="display:flex;justify-content:center"></div></div></div><div class="mo-f"><button class="btn-s" onclick="closeM()">'+t('c.cancel')+'</button><button class="btn-p" onclick="sB()">'+t('c.submit')+'</button></div>');uLP();['bn','br','be','bp','bv'].forEach(function(id){document.getElementById(id).addEventListener('input',uLP)});document.querySelectorAll('input[name="bs"]').forEach(function(r){r.addEventListener('change',uLP)})}
function uLP(){var d={name:document.getElementById('bn').value||'Name',role:document.getElementById('br').value||'Role',dept:cu.dept,employeeId:document.getElementById('be').value||'MF-000',phone:document.getElementById('bp').value||'---',validUntil:document.getElementById('bv').value||'2027-12-31',style:document.querySelector('input[name="bs"]:checked').value};document.getElementById('lp').innerHTML=rIC(d)}
function sB(){var name=document.getElementById('bn').value.trim(),eid=document.getElementById('be').value.trim();if(!name){toast('Name!');return}if(!eid){toast('ID!');return}var d=DB.get('badge',[]);var sq=String(d.length+1).padStart(3,'0');d.unshift({id:'B'+sq,name:name,role:document.getElementById('br').value||'Staff',dept:cu.dept,employeeId:eid,phone:document.getElementById('bp').value||'N/A',validUntil:document.getElementById('bv').value||'2027-12-31',style:document.querySelector('input[name="bs"]:checked').value,status:'processing'});DB.set('badge',d);closeM();rAll();toast('OK')}
function vB(id){var r=DB.get('badge',[]).find(function(x){return x.id===id});if(!r)return;openM('<div class="mo-h"><div class="mo-t">'+r.name+' / '+t('b.preview')+'</div><button class="mo-x" onclick="closeM()">&times;</button></div><div class="mo-b" style="display:flex;justify-content:center;padding:28px">'+rIC(r)+'</div><div class="mo-f"><button class="btn-s" onclick="closeM()">'+t('c.back')+'</button><button class="btn-p" onclick="window.print()">'+t('c.print')+'</button></div>')}
function cB(id){var d=DB.get('badge',[]);var r=d.find(function(x){return x.id===id});if(r){r.status='done';DB.set('badge',d);rAll()}}
function dB(id){var d=DB.get('badge',[]).filter(function(x){return x.id!==id});DB.set('badge',d);rAll()}
function rStats(){var r=myData('reimburse'),l=myData('leave'),tr=myData('travel'),b=myData('badge');var s=[{l:'s.pending',v:r.concat(l,tr).filter(function(x){return x.status==='pending'}).length},{l:'s.approved',v:r.concat(l,tr).filter(function(x){return x.status==='approved'}).length},{l:'s.total',v:r.length+l.length+tr.length+b.length},{l:'s.amount',v:fmtM(r.reduce(function(s,x){return s+Number(x.amount)},0)+tr.reduce(function(s,x){return s+Number(x.budget)},0))}];document.getElementById('oaStats').innerHTML=s.map(function(x){return'<div class="stat-box"><div class="num">'+x.v+'</div><div class="lbl">'+t(x.l)+'</div></div>'}).join('')}
function rMod(){var m={reimburse:rR,leave:rL,travel:rT,badge:rB};document.getElementById('mc').innerHTML=m[CM]()}
function rAll(){rStats();rMod()}
document.querySelectorAll('.oa-tab').forEach(function(tab){tab.addEventListener('click',function(){document.querySelectorAll('.oa-tab').forEach(function(t2){t2.classList.remove('active')});tab.classList.add('active');CM=tab.dataset.m;rMod()})});
var nav=document.getElementById('nav');window.addEventListener('scroll',function(){nav.classList.toggle('scrolled',window.scrollY>40)},{passive:true});
document.getElementById('navToggle').addEventListener('click',function(){document.getElementById('navLinks').classList.toggle('open')});
var obs=new IntersectionObserver(function(e){e.forEach(function(x){if(x.isIntersecting)x.target.classList.add('visible')})},{threshold:.1});document.querySelectorAll('.reveal').forEach(function(el){obs.observe(el)});
document.querySelectorAll('a[href$=".html"]').forEach(function(a){a.addEventListener('click',function(e){var h=a.getAttribute('href');if(h&&!h.startsWith('http')){e.preventDefault();document.body.style.opacity='0';document.body.style.transition='opacity .15s';setTimeout(function(){window.location.href=h},150)}})});
seed();rAll();
