package model

import (
	"errors"
	"fmt"
	"math/big"
	"net/url"
	"strconv"
	"strings"
	"time"

	gormsqlite "gorm.io/driver/sqlite"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var (
	ErrPointRefundUnavailable = errors.New("point refunds are unavailable on this database")
	ErrPointRefundInFlight    = errors.New("another refund for this order is still in progress")
	ErrPointRefundState       = errors.New("point refund state does not allow this operation")
)

type PointRefundRequest struct {
	UserID            int
	OrderKey          string
	IdempotencyKey    string
	RefundKey         string // generated by the trusted caller and never accepted from a client
	ProviderRefundKey string // immutable, channel-specific request key generated by the trusted caller
	AmountFen         int64
	Reason            string
}

type PointRefundEvidenceInput struct {
	EvidenceKey           string
	RefundKey             string
	OperationToken        string
	Provider              string
	Outcome               string // pending, succeeded, definite_failed, abnormal
	ProviderRefundID      string
	ProviderRefundKey     string
	OrderKey              string
	ProviderTransactionID string
	MerchantID            string
	AppID                 string
	AmountFen             int64
	TotalFen              int64
	Currency              string
	Digest                string
}

type PointRefundInboxInput struct {
	EvidenceKey           string
	RefundKey             string
	Provider              string
	EvidenceSource        string
	OperationToken        string
	ProviderEventID       string
	ProviderRefundID      string
	ProviderRefundKey     string
	OrderKey              string
	ProviderTransactionID string
	MerchantID            string
	AppID                 string
	Outcome               string
	ProviderStatus        string
	AmountFen             int64
	TotalFen              int64
	Currency              string
	ProviderOccurredAt    int64
	Digest                string
}

type PointRefundOperationClaim struct {
	Refund PointRefund
	Kind   string // apply or query; submitting after a crash always returns query.
}

func pointRefundDBReady(db *gorm.DB) error {
	if db == nil || db.Dialector == nil || db.Dialector.Name() != "sqlite" {
		return ErrPointRefundUnavailable
	}
	dialector, ok := db.Dialector.(*gormsqlite.Dialector)
	if !ok {
		return ErrPointRefundUnavailable
	}
	_, rawQuery, hasQuery := strings.Cut(dialector.DSN, "?")
	if !hasQuery {
		return fmt.Errorf("%w: SQLite immediate transaction mode is required", ErrPointRefundUnavailable)
	}
	values, err := url.ParseQuery(rawQuery)
	if err != nil || values.Get("_txlock") != "immediate" || values.Get("_busy_timeout") == "" {
		return fmt.Errorf("%w: SQLite immediate transaction mode is required", ErrPointRefundUnavailable)
	}
	busyTimeout, busyErr := strconv.Atoi(values.Get("_busy_timeout"))
	if values["_txlock"] == nil || len(values["_txlock"]) != 1 || len(values["_busy_timeout"]) != 1 || busyErr != nil || busyTimeout <= 0 {
		return fmt.Errorf("%w: SQLite transaction settings are ambiguous", ErrPointRefundUnavailable)
	}
	var migration PointsSchemaMigration
	if err := db.Where("version = ?", pointsSchemaVersion).First(&migration).Error; err != nil {
		return fmt.Errorf("point refund schema v%d is required: %w", pointsSchemaVersion, err)
	}
	return nil
}

func pointRefundTransaction(db *gorm.DB, fn func(*gorm.DB) error) error {
	if err := pointRefundDBReady(db); err != nil {
		return err
	}
	return pointsTransactionOn(db, fn)
}

// ClaimPointRefundOperation commits the provider operation claim before any
// network call. An expired submitting claim is query-only, so a crash after
// claim cannot blindly submit the same external refund again.
func ClaimPointRefundOperation(refundKey, token string, nowUnix, leaseSeconds int64) (*PointRefundOperationClaim, error) {
	return claimPointRefundOperationOn(DB, refundKey, token, nowUnix, leaseSeconds)
}

func claimPointRefundOperationOn(db *gorm.DB, refundKey, token string, nowUnix, leaseSeconds int64) (*PointRefundOperationClaim, error) {
	if refundKey == "" || token == "" || len(token) > 80 || nowUnix <= 0 || leaseSeconds <= 0 || leaseSeconds > int64(^uint64(0)>>1)-nowUnix {
		return nil, errors.New("invalid refund operation claim")
	}
	var result PointRefundOperationClaim
	err := pointRefundTransaction(db, func(tx *gorm.DB) error {
		result = PointRefundOperationClaim{}
		var refund PointRefund
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).Where("refund_key = ?", refundKey).First(&refund).Error; err != nil {
			return err
		}
		if refund.OperationToken != "" && nowUnix < refund.OperationLeaseUntil {
			return ErrPointRefundInFlight
		}
		kind := ""
		switch refund.State {
		case "approved":
			if refund.OperationClaimedAt != 0 && nowUnix >= refund.OperationLeaseUntil {
				kind = "query"
			} else {
				kind = "apply"
			}
		case "submitting", "submitted", "unknown", "needs_manual_review":
			kind = "query"
		default:
			return ErrPointRefundState
		}
		state := refund.State
		if kind == "apply" {
			state = "submitting"
		}
		leaseUntil := nowUnix + leaseSeconds
		updates := map[string]interface{}{"operation_token": token, "operation_kind": kind, "operation_claimed_at": nowUnix, "operation_lease_until": leaseUntil, "state": state, "updated_at": time.Unix(nowUnix, 0).UTC()}
		updated := tx.Model(&PointRefund{}).Where("id = ? AND operation_token = ? AND operation_claimed_at = ? AND operation_lease_until = ?", refund.ID, refund.OperationToken, refund.OperationClaimedAt, refund.OperationLeaseUntil).Updates(updates)
		if updated.Error != nil {
			return updated.Error
		}
		if updated.RowsAffected != 1 {
			return ErrPointRefundInFlight
		}
		refund.OperationToken, refund.OperationKind, refund.OperationClaimedAt, refund.OperationLeaseUntil, refund.State = token, kind, nowUnix, leaseUntil, state
		result = PointRefundOperationClaim{Refund: refund, Kind: kind}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func GetPointRefundByKey(refundKey string) (*PointRefund, error) {
	var refund PointRefund
	if err := pointRefundDBReady(DB); err != nil {
		return nil, err
	}
	if err := DB.Where("refund_key = ?", refundKey).First(&refund).Error; err != nil {
		return nil, err
	}
	return &refund, nil
}

func GetPointRefundForProvider(provider, providerRefundKey, orderKey string) (*PointRefund, error) {
	var refund PointRefund
	if err := pointRefundDBReady(DB); err != nil {
		return nil, err
	}
	if err := DB.Where("channel = ? AND provider_refund_key = ? AND order_key = ?", provider, providerRefundKey, orderKey).First(&refund).Error; err != nil {
		return nil, err
	}
	return &refund, nil
}

// PersistPointRefundInbox inserts only normalized verified evidence. It is
// intentionally separate from ledger processing so a crash leaves replayable
// work. Reuse of an evidence key with changed content is a conflict.
func PersistPointRefundInbox(input PointRefundInboxInput) (*PointRefundInbox, bool, error) {
	return persistPointRefundInboxOn(DB, input)
}

func persistPointRefundInboxOn(db *gorm.DB, input PointRefundInboxInput) (*PointRefundInbox, bool, error) {
	if input.EvidenceKey == "" || len(input.EvidenceKey) > 180 || input.RefundKey == "" || input.ProviderRefundKey == "" || input.OrderKey == "" || input.ProviderTransactionID == "" || input.MerchantID == "" || input.AppID == "" || input.AmountFen <= 0 || input.TotalFen <= 0 || input.Currency != "CNY" || input.Digest == "" || (input.Provider != "wechat" && input.Provider != "alipay") || (input.Outcome != "accepted" && input.Outcome != "succeeded" && input.Outcome != "definite_failed" && input.Outcome != "unknown" && input.Outcome != "abnormal") {
		return nil, false, errors.New("invalid normalized refund inbox evidence")
	}
	if input.EvidenceSource != "apply" && input.EvidenceSource != "query" && input.EvidenceSource != "notification" {
		return nil, false, errors.New("invalid refund evidence source")
	}
	var result PointRefundInbox
	duplicate := false
	err := pointRefundTransaction(db, func(tx *gorm.DB) error {
		result = PointRefundInbox{}
		duplicate = false
		var refund PointRefund
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).Where("refund_key = ?", input.RefundKey).First(&refund).Error; err != nil {
			return err
		}
		if refund.Channel != input.Provider || refund.ProviderRefundKey != input.ProviderRefundKey || refund.OrderKey != input.OrderKey || refund.ProviderTransactionID != input.ProviderTransactionID || refund.ProviderMerchantID != input.MerchantID || refund.ProviderAppID != input.AppID || refund.AmountFen != input.AmountFen || refund.OriginalAmountFen != input.TotalFen || refund.Currency != input.Currency {
			return errors.New("verified inbox evidence does not match the frozen refund")
		}
		result = PointRefundInbox{EvidenceKey: input.EvidenceKey, RefundKey: input.RefundKey, Provider: input.Provider, EvidenceSource: input.EvidenceSource, OperationToken: input.OperationToken, ProviderEventID: input.ProviderEventID, ProviderRefundID: input.ProviderRefundID, ProviderRefundKey: input.ProviderRefundKey, OrderKey: input.OrderKey, ProviderTransactionID: input.ProviderTransactionID, MerchantID: input.MerchantID, AppID: input.AppID, Outcome: input.Outcome, ProviderStatus: input.ProviderStatus, AmountFen: input.AmountFen, TotalFen: input.TotalFen, Currency: input.Currency, ProviderOccurredAt: input.ProviderOccurredAt, Digest: input.Digest, State: "received", CreatedAt: time.Now().UTC()}
		insert := tx.Clauses(clause.OnConflict{DoNothing: true}).Create(&result)
		if insert.Error != nil {
			return insert.Error
		}
		if insert.RowsAffected == 1 {
			return nil
		}
		duplicate = true
		var prior PointRefundInbox
		if err := tx.Where("evidence_key = ?", input.EvidenceKey).First(&prior).Error; err != nil {
			return err
		}
		if !samePointRefundInbox(prior, input) {
			return ErrPointsConflict
		}
		result = prior
		return nil
	})
	if err != nil {
		return nil, false, err
	}
	return &result, duplicate, nil
}

func samePointRefundInbox(old PointRefundInbox, input PointRefundInboxInput) bool {
	return old.RefundKey == input.RefundKey && old.Provider == input.Provider && old.EvidenceSource == input.EvidenceSource && old.OperationToken == input.OperationToken && old.ProviderEventID == input.ProviderEventID && old.ProviderRefundID == input.ProviderRefundID && old.ProviderRefundKey == input.ProviderRefundKey && old.OrderKey == input.OrderKey && old.ProviderTransactionID == input.ProviderTransactionID && old.MerchantID == input.MerchantID && old.AppID == input.AppID && old.Outcome == input.Outcome && old.ProviderStatus == input.ProviderStatus && old.AmountFen == input.AmountFen && old.TotalFen == input.TotalFen && old.Currency == input.Currency && old.ProviderOccurredAt == input.ProviderOccurredAt && old.Digest == input.Digest
}

func ListReceivedPointRefundInbox(afterID uint, limit int) ([]PointRefundInbox, bool, error) {
	if limit <= 0 || limit > 500 {
		return nil, false, errors.New("invalid refund inbox scan limit")
	}
	if err := pointRefundDBReady(DB); err != nil {
		return nil, false, err
	}
	var rows []PointRefundInbox
	err := DB.Where("state = ? AND id > ?", "received", afterID).Order("id ASC").Limit(limit + 1).Find(&rows).Error
	if err != nil {
		return nil, false, err
	}
	hasMore := len(rows) > limit
	if hasMore {
		rows = rows[:limit]
	}
	return rows, hasMore, nil
}

func MarkPointRefundInbox(inboxID uint, state, errorCode string, processedAt time.Time) error {
	if inboxID == 0 || (state != "processed" && state != "quarantined") || len(errorCode) > 48 {
		return errors.New("invalid refund inbox state")
	}
	return pointRefundTransaction(DB, func(tx *gorm.DB) error {
		updates := map[string]interface{}{"state": state, "error_code": errorCode, "processed_at": processedAt.UTC()}
		result := tx.Model(&PointRefundInbox{}).Where("id = ? AND state = ?", inboxID, "received").Updates(updates)
		if result.Error != nil {
			return result.Error
		}
		if result.RowsAffected == 0 {
			var existing PointRefundInbox
			if err := tx.First(&existing, inboxID).Error; err != nil {
				return err
			}
			if existing.State == state && existing.ErrorCode == errorCode {
				return nil
			}
			return ErrPointsConflict
		}
		return nil
	})
}

// RecordPointRefundOperationUnknown consumes a persisted transport/decoding
// uncertainty without inventing provider evidence or a WeChat refund ID.
// Only the current claim token can clear the lease; stale workers are harmless.
func RecordPointRefundOperationUnknown(refundKey, operationToken string, now time.Time) error {
	if refundKey == "" || operationToken == "" || len(operationToken) > 80 {
		return errors.New("refund operation token is required")
	}
	return pointRefundTransaction(DB, func(tx *gorm.DB) error {
		var refund PointRefund
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).Where("refund_key = ?", refundKey).First(&refund).Error; err != nil {
			return err
		}
		if refund.State == "succeeded" || refund.State == "definite_failed" || refund.State == "rejected" {
			return nil
		}
		if refund.OperationToken != operationToken {
			if (refund.State == "unknown" || refund.State == "needs_manual_review") && refund.OperationToken == "" {
				return nil // Replay after state commit but before inbox mark.
			}
			return nil // A late transport error cannot clear a newer lease.
		}
		state := refund.State
		if state != "needs_manual_review" {
			state = "unknown"
		}
		updates := map[string]interface{}{"state": state, "updated_at": now.UTC()}
		clearPointRefundOperation(updates)
		return tx.Model(&PointRefund{}).Where("id = ? AND operation_token = ?", refund.ID, operationToken).Updates(updates).Error
	})
}

func RequestPointRefund(req PointRefundRequest) (*PointRefund, error) {
	return requestPointRefundOn(DB, req)
}

func requestPointRefundOn(db *gorm.DB, req PointRefundRequest) (*PointRefund, error) {
	if req.UserID <= 0 || req.OrderKey == "" || req.IdempotencyKey == "" || req.AmountFen <= 0 || req.Reason == "" || len(req.Reason) > 512 {
		return nil, errors.New("invalid point refund request")
	}
	if req.RefundKey == "" || len(req.RefundKey) > 180 || req.ProviderRefundKey == "" || len(req.ProviderRefundKey) > 64 {
		return nil, errors.New("trusted refund identifiers are required")
	}
	var result PointRefund
	err := pointRefundTransaction(db, func(tx *gorm.DB) error {
		result = PointRefund{} // pointsTransaction may safely retry a BUSY transaction.
		var prior PointRefund
		err := tx.Where("user_id = ? AND order_key = ? AND idempotency_key = ?", req.UserID, req.OrderKey, req.IdempotencyKey).First(&prior).Error
		if err == nil {
			if prior.AmountFen != req.AmountFen || prior.Reason != req.Reason {
				return ErrPointsConflict
			}
			result = prior
			return nil
		}
		if !errors.Is(err, gorm.ErrRecordNotFound) {
			return err
		}
		now := time.Now().UTC()
		if err := expireAvailablePointLotsTx(tx, req.UserID, now); err != nil {
			return err
		}
		var order PointPurchaseOrder
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).Where("order_key = ? AND user_id = ?", req.OrderKey, req.UserID).First(&order).Error; err != nil {
			return err
		}
		if order.State != "credited" && order.State != "refunded" {
			return ErrPointRefundState
		}
		if order.Channel != "wechat" && order.Channel != "alipay" || order.Currency != "CNY" || order.ProviderMerchantID == "" || order.ProviderAppID == "" || order.ProviderTransactionID == "" {
			return errors.New("order does not have a complete refundable payment identity")
		}
		if order.AmountFen <= 0 || order.AmountFen > int64(^uint64(0)>>1)/PointMicroPerPoint || order.PurchaseMicro != order.AmountFen*PointMicroPerPoint || req.AmountFen > order.AmountFen {
			return errors.New("invalid original purchase amount")
		}
		var activeCount int64
		if err := tx.Model(&PointRefund{}).Where("order_key = ? AND active_order_key IS NOT NULL", order.OrderKey).Count(&activeCount).Error; err != nil {
			return err
		}
		if activeCount != 0 {
			return ErrPointRefundInFlight
		}
		var purchase PointLot
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).Where("business_key = ?", "purchase:"+order.OrderKey).First(&purchase).Error; err != nil {
			return err
		}
		if purchase.UserID != order.UserID || purchase.Kind != "purchase" || purchase.InitialMicro != order.PurchaseMicro || purchase.AmountFen != order.AmountFen || purchase.RefundedMicro%PointMicroPerPoint != 0 {
			return errors.New("purchase lot does not match the immutable order snapshot")
		}
		if err := validatePointLotConservation(purchase); err != nil {
			return err
		}
		purchaseMicro, err := checkedMulPointRefund(req.AmountFen)
		if err != nil {
			return err
		}
		var priorRefunds []PointRefund
		if err := tx.Where("order_key = ? AND state = ?", order.OrderKey, "succeeded").Find(&priorRefunds).Error; err != nil {
			return err
		}
		var refundedFen int64
		for _, old := range priorRefunds {
			refundedFen, err = checkedAdd(refundedFen, old.AmountFen)
			if err != nil {
				return err
			}
		}
		cumulativeFen, err := checkedAdd(refundedFen, req.AmountFen)
		if err != nil || cumulativeFen > order.AmountFen {
			return ErrPointsInsufficient
		}
		if purchase.RefundedMicro != refundedFen*PointMicroPerPoint {
			return errors.New("purchase refund counters do not match completed refund records")
		}
		if purchase.AvailableMicro < purchaseMicro {
			return ErrPointsInsufficient
		}

		bonusMicro := int64(0)
		var bonus PointLot
		if order.BonusMicro > 0 {
			if order.BonusExpiresAt == nil {
				return errors.New("order bonus has no immutable expiry")
			}
			if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).Where("business_key = ?", "bonus:"+order.OrderKey).First(&bonus).Error; err != nil {
				return err
			}
			if bonus.UserID != order.UserID || bonus.Kind != "bonus" || bonus.InitialMicro != order.BonusMicro || bonus.ExpiresAt == nil || *bonus.ExpiresAt != *order.BonusExpiresAt {
				return errors.New("bonus lot does not match the immutable order snapshot")
			}
			if err := validatePointLotConservation(bonus); err != nil {
				return err
			}
			target, err := cumulativeBonusTarget(order.BonusMicro, cumulativeFen, order.AmountFen)
			if err != nil {
				return err
			}
			accounted, err := checkedAdd(bonus.RevokedMicro, bonus.ExpiredMicro)
			if err != nil {
				return err
			}
			if accounted < target {
				bonusMicro = target - accounted
			}
			if bonus.AvailableMicro < bonusMicro {
				return ErrPointsInsufficient
			}
		}
		total, err := checkedAdd(purchaseMicro, bonusMicro)
		if err != nil {
			return err
		}
		var account PointAccount
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).Where("user_id = ?", order.UserID).First(&account).Error; err != nil {
			return err
		}
		nextHeld, err := checkedAdd(account.HeldMicro, total)
		if err != nil || nextHeld < 0 {
			return errors.New("account held balance overflow")
		}
		accountUpdate := tx.Model(&PointAccount{}).Where("user_id = ? AND available_micro >= ?", order.UserID, total).Updates(map[string]interface{}{
			"available_micro": gorm.Expr("available_micro - ?", total),
			"held_micro":      gorm.Expr("held_micro + ?", total),
		})
		if accountUpdate.Error != nil {
			return accountUpdate.Error
		}
		if accountUpdate.RowsAffected != 1 {
			return ErrPointsInsufficient
		}
		purchaseUpdate := tx.Model(&PointLot{}).Where("id = ? AND available_micro >= ?", purchase.ID, purchaseMicro).Updates(map[string]interface{}{
			"available_micro": gorm.Expr("available_micro - ?", purchaseMicro),
			"held_micro":      gorm.Expr("held_micro + ?", purchaseMicro),
		})
		if purchaseUpdate.Error != nil {
			return purchaseUpdate.Error
		}
		if purchaseUpdate.RowsAffected != 1 {
			return ErrPointsInsufficient
		}
		if bonusMicro > 0 {
			bonusUpdate := tx.Model(&PointLot{}).Where("id = ? AND available_micro >= ? AND (expires_at IS NULL OR expires_at > ?)", bonus.ID, bonusMicro, now.Unix()).Updates(map[string]interface{}{
				"available_micro": gorm.Expr("available_micro - ?", bonusMicro),
				"held_micro":      gorm.Expr("held_micro + ?", bonusMicro),
			})
			if bonusUpdate.Error != nil {
				return bonusUpdate.Error
			}
			if bonusUpdate.RowsAffected != 1 {
				return ErrPointsInsufficient
			}
		}
		idempotency := req.IdempotencyKey
		active := order.OrderKey
		result = PointRefund{RefundKey: req.RefundKey, UserID: req.UserID, OrderKey: order.OrderKey, IdempotencyKey: &idempotency, ActiveOrderKey: &active, Channel: order.Channel, ProviderMerchantID: order.ProviderMerchantID, ProviderAppID: order.ProviderAppID, ProviderTransactionID: order.ProviderTransactionID, ProviderRefundKey: req.ProviderRefundKey, PriorRefundedFen: refundedFen, Currency: order.Currency, AmountFen: req.AmountFen, PurchaseMicro: purchaseMicro, BonusRevokeMicro: bonusMicro, OriginalAmountFen: order.AmountFen, OriginalPurchaseMicro: order.PurchaseMicro, OriginalBonusMicro: order.BonusMicro, Reason: req.Reason, State: "awaiting_review", CreatedAt: now, UpdatedAt: now}
		if err := tx.Create(&result).Error; err != nil {
			return err
		}
		if err := tx.Create(&PointRefundAllocation{RefundID: result.ID, LotID: purchase.ID, LotKind: "purchase", PurchaseMicro: purchaseMicro, CreatedAt: now}).Error; err != nil {
			return err
		}
		if bonusMicro > 0 {
			if err := tx.Create(&PointRefundAllocation{RefundID: result.ID, LotID: bonus.ID, LotKind: "bonus", BonusMicro: bonusMicro, CreatedAt: now}).Error; err != nil {
				return err
			}
		}
		var updated PointAccount
		if err := tx.First(&updated, "user_id = ?", order.UserID).Error; err != nil {
			return err
		}
		return tx.Create(&PointLedger{UserID: order.UserID, BusinessKey: "refund-hold:" + result.RefundKey, Kind: "refund_hold", AvailableDelta: -total, HeldDelta: total, AvailableAfter: updated.AvailableMicro, HeldAfter: updated.HeldMicro, SpentAfter: updated.SpentMicro, Reason: "refund amount reserved"}).Error
	})
	if err != nil {
		return nil, err
	}
	return &result, nil
}

func checkedMulPointRefund(amountFen int64) (int64, error) {
	if amountFen <= 0 || amountFen > int64(^uint64(0)>>1)/PointMicroPerPoint {
		return 0, errors.New("refund amount is out of range")
	}
	return amountFen * PointMicroPerPoint, nil
}

func cumulativeBonusTarget(originalBonus, cumulativeFen, originalFen int64) (int64, error) {
	if originalBonus < 0 || cumulativeFen < 0 || originalFen <= 0 || cumulativeFen > originalFen {
		return 0, errors.New("invalid cumulative refund amount")
	}
	if cumulativeFen == originalFen {
		return originalBonus, nil
	}
	numerator := new(big.Int).Mul(big.NewInt(originalBonus), big.NewInt(cumulativeFen))
	numerator.Quo(numerator, big.NewInt(originalFen))
	if !numerator.IsInt64() {
		return 0, errors.New("bonus refund target overflow")
	}
	return numerator.Int64(), nil
}

func ApprovePointRefund(refundKey, decisionKey string, actorID int, reason string) error {
	return decidePointRefundOn(DB, refundKey, decisionKey, actorID, "approve", reason)
}

func RejectPointRefund(refundKey, decisionKey string, actorID int, reason string) error {
	return decidePointRefundOn(DB, refundKey, decisionKey, actorID, "reject", reason)
}

func decidePointRefundOn(db *gorm.DB, refundKey, decisionKey string, actorID int, action, reason string) error {
	if refundKey == "" || decisionKey == "" || actorID <= 0 || (action != "approve" && action != "reject") || len(reason) > 512 {
		return errors.New("invalid refund decision")
	}
	return pointRefundTransaction(db, func(tx *gorm.DB) error {
		var refund PointRefund
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).Where("refund_key = ?", refundKey).First(&refund).Error; err != nil {
			return err
		}
		var prior PointRefundDecision
		err := tx.Where("decision_key = ?", decisionKey).First(&prior).Error
		if err == nil {
			if prior.RefundID == refund.ID && prior.ActorUserID == actorID && prior.Action == action && prior.Reason == reason {
				return nil
			}
			return ErrPointsConflict
		}
		if !errors.Is(err, gorm.ErrRecordNotFound) {
			return err
		}
		if refund.State != "awaiting_review" {
			return ErrPointRefundState
		}
		now := time.Now().UTC()
		decision := PointRefundDecision{RefundID: refund.ID, DecisionKey: decisionKey, ActorUserID: actorID, Action: action, Reason: reason, CreatedAt: now}
		if err := tx.Create(&decision).Error; err != nil {
			return err
		}
		if action == "approve" {
			upd := tx.Model(&PointRefund{}).Where("id = ? AND state = ?", refund.ID, "awaiting_review").Updates(map[string]interface{}{"state": "approved", "updated_at": now})
			if upd.Error != nil {
				return upd.Error
			}
			if upd.RowsAffected != 1 {
				return ErrPointRefundState
			}
			return nil
		}
		if err := releasePointRefundTx(tx, &refund, "rejected", now); err != nil {
			return err
		}
		if err := tx.Model(&PointRefund{}).Where("id = ? AND state = ?", refund.ID, "awaiting_review").Updates(map[string]interface{}{"state": "rejected", "active_order_key": nil, "updated_at": now}).Error; err != nil {
			return err
		}
		return nil
	})
}

func RecordPointRefundEvidence(input PointRefundEvidenceInput) error {
	return recordPointRefundEvidenceOn(DB, input)
}

func recordPointRefundEvidenceOn(db *gorm.DB, input PointRefundEvidenceInput) error {
	if input.EvidenceKey == "" || input.RefundKey == "" || input.OrderKey == "" || input.ProviderTransactionID == "" || input.MerchantID == "" || input.AppID == "" || input.ProviderRefundKey == "" || len(input.ProviderRefundKey) > 64 || input.AmountFen <= 0 || input.TotalFen <= 0 || input.Currency != "CNY" || input.Digest == "" || (input.Provider != "wechat" && input.Provider != "alipay") || (input.Outcome != "pending" && input.Outcome != "succeeded" && input.Outcome != "definite_failed" && input.Outcome != "abnormal" && input.Outcome != "unknown") {
		return errors.New("invalid verified refund evidence")
	}
	return pointRefundTransaction(db, func(tx *gorm.DB) error {
		var refund PointRefund
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).Where("refund_key = ?", input.RefundKey).First(&refund).Error; err != nil {
			return err
		}
		if input.Provider != refund.Channel || input.OrderKey != refund.OrderKey || input.ProviderTransactionID != refund.ProviderTransactionID || input.MerchantID != refund.ProviderMerchantID || input.AppID != refund.ProviderAppID || input.ProviderRefundKey != refund.ProviderRefundKey || input.AmountFen != refund.AmountFen || input.TotalFen != refund.OriginalAmountFen || input.Currency != refund.Currency {
			return errors.New("verified refund evidence does not match the frozen refund")
		}
		var old PointRefundEvidence
		err := tx.Where("evidence_key = ?", input.EvidenceKey).First(&old).Error
		if err == nil {
			if !samePointRefundEvidence(old, input) {
				return ErrPointsConflict
			}
			return nil
		}
		if !errors.Is(err, gorm.ErrRecordNotFound) {
			return err
		}
		if refund.State == "succeeded" {
			if input.Outcome != "succeeded" {
				// Late nonterminal provider replies remain evidence, but cannot
				// downgrade a completed refund or mutate its ledger again.
				return nil
			}
		} else if refund.State != "approved" && refund.State != "submitting" && refund.State != "submitted" && refund.State != "unknown" && refund.State != "needs_manual_review" {
			return ErrPointRefundState
		}
		providerOwnerID := ""
		if input.Provider == "alipay" {
			providerOwnerID = input.ProviderRefundKey // Alipay's out_request_no is the stable refund identity.
		} else {
			providerOwnerID = input.ProviderRefundID
			if providerOwnerID == "" {
				return errors.New("verified WeChat refund id is required")
			}
		}
		if providerOwnerID != "" {
			var owner PointRefundProviderOwner
			err := tx.Where("provider = ? AND merchant_id = ? AND provider_refund_id = ?", input.Provider, input.MerchantID, providerOwnerID).First(&owner).Error
			if err == nil && owner.RefundKey != refund.RefundKey {
				return ErrPointsConflict
			}
			if errors.Is(err, gorm.ErrRecordNotFound) {
				owner = PointRefundProviderOwner{Provider: input.Provider, MerchantID: input.MerchantID, ProviderRefundID: providerOwnerID, RefundKey: refund.RefundKey}
				if err := tx.Create(&owner).Error; err != nil {
					return err
				}
			} else if err != nil {
				return err
			}
		}
		var previous []PointRefundEvidence
		if err := tx.Where("refund_key = ?", refund.RefundKey).Find(&previous).Error; err != nil {
			return err
		}
		for _, priorEvidence := range previous {
			if priorEvidence.ProviderRefundKey != input.ProviderRefundKey || (priorEvidence.ProviderRefundID != "" && input.ProviderRefundID != "" && priorEvidence.ProviderRefundID != input.ProviderRefundID) {
				return ErrPointsConflict
			}
		}
		evidence := PointRefundEvidence{EvidenceKey: input.EvidenceKey, RefundKey: input.RefundKey, Provider: input.Provider, Outcome: input.Outcome, ProviderRefundID: input.ProviderRefundID, ProviderRefundKey: input.ProviderRefundKey, OrderKey: input.OrderKey, ProviderTransactionID: input.ProviderTransactionID, MerchantID: input.MerchantID, AppID: input.AppID, AmountFen: input.AmountFen, TotalFen: input.TotalFen, Currency: input.Currency, Digest: input.Digest, CreatedAt: time.Now().UTC()}
		if err := tx.Create(&evidence).Error; err != nil {
			return err
		}
		if refund.State == "succeeded" {
			return nil // A second signed event for the same external refund is evidence only.
		}
		now := time.Now().UTC()
		switch input.Outcome {
		case "pending":
			if refund.State == "needs_manual_review" {
				if input.OperationToken != "" && refund.OperationToken == input.OperationToken {
					updates := map[string]interface{}{"updated_at": now}
					clearPointRefundOperation(updates)
					return tx.Model(&PointRefund{}).Where("id = ? AND operation_token = ?", refund.ID, input.OperationToken).Updates(updates).Error
				}
				return nil
			}
			if input.OperationToken != "" && refund.OperationToken != input.OperationToken {
				return nil
			}
			updates := map[string]interface{}{"state": "submitted", "updated_at": now}
			if input.OperationToken != "" && refund.OperationToken == input.OperationToken {
				clearPointRefundOperation(updates)
			}
			return tx.Model(&PointRefund{}).Where("id = ?", refund.ID).Updates(updates).Error
		case "unknown":
			if refund.State == "needs_manual_review" {
				if input.OperationToken != "" && refund.OperationToken == input.OperationToken {
					updates := map[string]interface{}{"updated_at": now}
					clearPointRefundOperation(updates)
					return tx.Model(&PointRefund{}).Where("id = ? AND operation_token = ?", refund.ID, input.OperationToken).Updates(updates).Error
				}
				return nil
			}
			if input.OperationToken != "" && refund.OperationToken != input.OperationToken {
				return nil
			}
			updates := map[string]interface{}{"state": "unknown", "updated_at": now}
			if input.OperationToken != "" && refund.OperationToken == input.OperationToken {
				clearPointRefundOperation(updates)
			}
			return tx.Model(&PointRefund{}).Where("id = ?", refund.ID).Updates(updates).Error
		case "abnormal":
			if input.OperationToken != "" && refund.OperationToken != input.OperationToken {
				return nil
			}
			updates := map[string]interface{}{"state": "needs_manual_review", "updated_at": now}
			if input.OperationToken != "" && refund.OperationToken == input.OperationToken {
				clearPointRefundOperation(updates)
			}
			return tx.Model(&PointRefund{}).Where("id = ?", refund.ID).Updates(updates).Error
		case "definite_failed":
			if err := releasePointRefundTx(tx, &refund, "definite_failed", now); err != nil {
				return err
			}
			return tx.Model(&PointRefund{}).Where("id = ?", refund.ID).Updates(map[string]interface{}{"state": "definite_failed", "active_order_key": nil, "operation_token": "", "operation_kind": "", "operation_claimed_at": 0, "operation_lease_until": 0, "updated_at": now}).Error
		case "succeeded":
			return finalizePointRefundTx(tx, &refund, now)
		default:
			return errors.New("unsupported refund evidence outcome")
		}
	})
}

func samePointRefundEvidence(old PointRefundEvidence, input PointRefundEvidenceInput) bool {
	return old.RefundKey == input.RefundKey && old.Provider == input.Provider && old.Outcome == input.Outcome && old.ProviderRefundID == input.ProviderRefundID && old.ProviderRefundKey == input.ProviderRefundKey && old.OrderKey == input.OrderKey && old.ProviderTransactionID == input.ProviderTransactionID && old.MerchantID == input.MerchantID && old.AppID == input.AppID && old.AmountFen == input.AmountFen && old.TotalFen == input.TotalFen && old.Currency == input.Currency && old.Digest == input.Digest
}

func clearPointRefundOperation(updates map[string]interface{}) {
	updates["operation_token"] = ""
	updates["operation_kind"] = ""
	updates["operation_claimed_at"] = 0
	updates["operation_lease_until"] = 0
}

func refundAllocationsTx(tx *gorm.DB, refundID uint) ([]PointRefundAllocation, error) {
	var allocations []PointRefundAllocation
	err := tx.Where("refund_id = ?", refundID).Order("id ASC").Find(&allocations).Error
	return allocations, err
}

func releasePointRefundTx(tx *gorm.DB, refund *PointRefund, state string, now time.Time) error {
	allocations, err := validatedPointRefundAllocationsTx(tx, refund)
	if err != nil {
		return err
	}
	var total, availableRelease int64
	for _, allocation := range allocations {
		amount, err := checkedAdd(allocation.PurchaseMicro, allocation.BonusMicro)
		if err != nil {
			return err
		}
		if amount < 0 {
			return errors.New("negative refund allocation")
		}
		total, err = checkedAdd(total, amount)
		if err != nil {
			return err
		}
		var lot PointLot
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&lot, allocation.LotID).Error; err != nil {
			return err
		}
		if err := validatePointLotConservation(lot); err != nil {
			return err
		}
		if lot.HeldMicro < amount {
			return errors.New("refund lot held amount is smaller than its allocation")
		}
		updates := map[string]interface{}{"held_micro": gorm.Expr("held_micro - ?", amount)}
		isExpired := lot.ExpiresAt != nil && *lot.ExpiresAt <= now.Unix()
		if isExpired {
			next, addErr := checkedAdd(lot.ExpiredMicro, amount)
			accounted, accountedErr := checkedAdd(next, lot.AvailableMicro)
			if addErr != nil || accountedErr != nil || accounted > lot.InitialMicro {
				return errors.New("expired refund allocation exceeds original lot")
			}
			updates["expired_micro"] = gorm.Expr("expired_micro + ?", amount)
		} else {
			next, addErr := checkedAdd(lot.AvailableMicro, amount)
			if addErr != nil || next > lot.InitialMicro {
				return errors.New("released refund allocation exceeds original lot")
			}
			updates["available_micro"] = gorm.Expr("available_micro + ?", amount)
			availableRelease, err = checkedAdd(availableRelease, amount)
			if err != nil {
				return err
			}
		}
		update := tx.Model(&PointLot{}).Where("id = ? AND held_micro >= ?", lot.ID, amount).Updates(updates)
		if update.Error != nil {
			return update.Error
		}
		if update.RowsAffected != 1 {
			return errors.New("refund lot reservation changed")
		}
	}
	var account PointAccount
	if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&account, "user_id = ?", refund.UserID).Error; err != nil {
		return err
	}
	accountUpdate := tx.Model(&PointAccount{}).Where("user_id = ? AND held_micro >= ? AND available_micro <= ?", refund.UserID, total, int64(^uint64(0)>>1)-availableRelease).Updates(map[string]interface{}{
		"held_micro":      gorm.Expr("held_micro - ?", total),
		"available_micro": gorm.Expr("available_micro + ?", availableRelease),
	})
	if accountUpdate.Error != nil {
		return accountUpdate.Error
	}
	if accountUpdate.RowsAffected != 1 {
		return errors.New("refund account reservation changed")
	}
	var updated PointAccount
	if err := tx.First(&updated, "user_id = ?", refund.UserID).Error; err != nil {
		return err
	}
	return tx.Create(&PointLedger{UserID: refund.UserID, BusinessKey: "refund-release:" + refund.RefundKey, Kind: "refund_release", AvailableDelta: availableRelease, HeldDelta: -total, AvailableAfter: updated.AvailableMicro, HeldAfter: updated.HeldMicro, SpentAfter: updated.SpentMicro, Reason: state}).Error
}

func finalizePointRefundTx(tx *gorm.DB, refund *PointRefund, now time.Time) error {
	allocations, err := validatedPointRefundAllocationsTx(tx, refund)
	if err != nil {
		return err
	}
	var total int64
	for _, allocation := range allocations {
		amount, err := checkedAdd(allocation.PurchaseMicro, allocation.BonusMicro)
		if err != nil || amount <= 0 {
			return errors.New("invalid refund allocation")
		}
		total, err = checkedAdd(total, amount)
		if err != nil {
			return err
		}
		var lot PointLot
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&lot, allocation.LotID).Error; err != nil {
			return err
		}
		if err := validatePointLotConservation(lot); err != nil {
			return err
		}
		if lot.HeldMicro < amount {
			return errors.New("refund lot held amount is smaller than its allocation")
		}
		updates := map[string]interface{}{"held_micro": gorm.Expr("held_micro - ?", amount)}
		if allocation.PurchaseMicro > 0 {
			next, addErr := checkedAdd(lot.RefundedMicro, allocation.PurchaseMicro)
			if addErr != nil || next > lot.InitialMicro {
				return errors.New("purchase refund exceeds original lot")
			}
			updates["refunded_micro"] = gorm.Expr("refunded_micro + ?", allocation.PurchaseMicro)
		}
		if allocation.BonusMicro > 0 {
			next, addErr := checkedAdd(lot.RevokedMicro, allocation.BonusMicro)
			accounted, accountedErr := checkedAdd(next, lot.ExpiredMicro)
			if addErr != nil || accountedErr != nil || accounted > lot.InitialMicro {
				return errors.New("bonus revocation exceeds original lot")
			}
			updates["revoked_micro"] = gorm.Expr("revoked_micro + ?", allocation.BonusMicro)
		}
		update := tx.Model(&PointLot{}).Where("id = ? AND held_micro >= ? AND initial_micro >= ?", lot.ID, amount, amount).Updates(updates)
		if update.Error != nil {
			return update.Error
		}
		if update.RowsAffected != 1 {
			return errors.New("refund lot reservation changed")
		}
	}
	var account PointAccount
	if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&account, "user_id = ?", refund.UserID).Error; err != nil {
		return err
	}
	update := tx.Model(&PointAccount{}).Where("user_id = ? AND held_micro >= ?", refund.UserID, total).Update("held_micro", gorm.Expr("held_micro - ?", total))
	if update.Error != nil {
		return update.Error
	}
	if update.RowsAffected != 1 {
		return errors.New("refund account reservation changed")
	}
	var updated PointAccount
	if err := tx.First(&updated, "user_id = ?", refund.UserID).Error; err != nil {
		return err
	}
	if err := tx.Create(&PointLedger{UserID: refund.UserID, BusinessKey: "refund-success:" + refund.RefundKey, Kind: "refund_settle", HeldDelta: -total, AvailableAfter: updated.AvailableMicro, HeldAfter: updated.HeldMicro, SpentAfter: updated.SpentMicro, Reason: "verified provider refund completed"}).Error; err != nil {
		return err
	}
	var order PointPurchaseOrder
	if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).Where("order_key = ?", refund.OrderKey).First(&order).Error; err != nil {
		return err
	}
	if order.UserID != refund.UserID || order.Channel != refund.Channel || order.ProviderMerchantID != refund.ProviderMerchantID || order.ProviderAppID != refund.ProviderAppID || order.ProviderTransactionID != refund.ProviderTransactionID || order.Currency != refund.Currency || order.AmountFen != refund.OriginalAmountFen || order.PurchaseMicro != refund.OriginalPurchaseMicro || order.BonusMicro != refund.OriginalBonusMicro {
		return errors.New("original purchase order no longer matches the frozen refund identity")
	}
	var refundedFen int64
	if err := tx.Model(&PointRefund{}).Where("order_key = ? AND state IN ?", refund.OrderKey, []string{"succeeded"}).Select("COALESCE(SUM(amount_fen), 0)").Scan(&refundedFen).Error; err != nil {
		return err
	}
	refundedFen, err = checkedAdd(refundedFen, refund.AmountFen)
	if err != nil {
		return err
	}
	if refundedFen > order.AmountFen {
		return errors.New("completed refunds exceed the original order amount")
	}
	if refundedFen == order.AmountFen {
		orderUpdate := tx.Model(&PointPurchaseOrder{}).Where("id = ? AND state IN ?", order.ID, []string{"credited", "refunded"}).Update("state", "refunded")
		if orderUpdate.Error != nil {
			return orderUpdate.Error
		}
		if orderUpdate.RowsAffected != 1 {
			return ErrPointRefundState
		}
	}
	refundUpdate := tx.Model(&PointRefund{}).Where("id = ? AND state IN ?", refund.ID, []string{"approved", "submitting", "submitted", "unknown", "needs_manual_review"}).Updates(map[string]interface{}{"state": "succeeded", "active_order_key": nil, "operation_token": "", "operation_kind": "", "operation_claimed_at": 0, "operation_lease_until": 0, "updated_at": now})
	if refundUpdate.Error != nil {
		return refundUpdate.Error
	}
	if refundUpdate.RowsAffected != 1 {
		return ErrPointRefundState
	}
	return nil
}

func validatedPointRefundAllocationsTx(tx *gorm.DB, refund *PointRefund) ([]PointRefundAllocation, error) {
	expectedPurchase, err := checkedMulPointRefund(refund.AmountFen)
	if err != nil || expectedPurchase != refund.PurchaseMicro || refund.OriginalAmountFen <= 0 || refund.OriginalAmountFen > int64(^uint64(0)>>1)/PointMicroPerPoint || refund.OriginalPurchaseMicro != refund.OriginalAmountFen*PointMicroPerPoint || refund.AmountFen > refund.OriginalAmountFen {
		return nil, errors.New("refund amounts do not match immutable order snapshot")
	}
	allocations, err := refundAllocationsTx(tx, refund.ID)
	if err != nil {
		return nil, err
	}
	var purchaseMicro, bonusMicro int64
	seenPurchase, seenBonus := false, false
	for _, allocation := range allocations {
		if allocation.PurchaseMicro < 0 || allocation.BonusMicro < 0 || (allocation.PurchaseMicro == 0) == (allocation.BonusMicro == 0) {
			return nil, errors.New("invalid refund allocation shape")
		}
		var lot PointLot
		if err := tx.First(&lot, allocation.LotID).Error; err != nil {
			return nil, err
		}
		if err := validatePointLotConservation(lot); err != nil {
			return nil, err
		}
		if lot.UserID != refund.UserID || lot.SourceRef != refund.OrderKey {
			return nil, errors.New("refund allocation belongs to another user or order")
		}
		switch allocation.LotKind {
		case "purchase":
			if seenPurchase || allocation.PurchaseMicro == 0 || allocation.BonusMicro != 0 || lot.Kind != "purchase" || lot.BusinessKey != "purchase:"+refund.OrderKey || lot.InitialMicro != refund.OriginalPurchaseMicro {
				return nil, errors.New("refund purchase allocation does not match order snapshot")
			}
			seenPurchase = true
			purchaseMicro, err = checkedAdd(purchaseMicro, allocation.PurchaseMicro)
		case "bonus":
			if seenBonus || allocation.BonusMicro == 0 || allocation.PurchaseMicro != 0 || lot.Kind != "bonus" || lot.BusinessKey != "bonus:"+refund.OrderKey || lot.InitialMicro != refund.OriginalBonusMicro {
				return nil, errors.New("refund bonus allocation does not match order snapshot")
			}
			seenBonus = true
			bonusMicro, err = checkedAdd(bonusMicro, allocation.BonusMicro)
		default:
			return nil, errors.New("unknown refund allocation lot kind")
		}
		if err != nil {
			return nil, err
		}
	}
	if !seenPurchase || purchaseMicro != refund.PurchaseMicro || bonusMicro != refund.BonusRevokeMicro || seenBonus != (refund.BonusRevokeMicro > 0) {
		return nil, errors.New("refund allocation totals do not match immutable request")
	}
	return allocations, nil
}

func validatePointLotConservation(lot PointLot) error {
	values := []int64{lot.AvailableMicro, lot.HeldMicro, lot.ConsumedMicro, lot.RefundedMicro, lot.RevokedMicro, lot.ExpiredMicro}
	var accounted int64
	for _, value := range values {
		if value < 0 {
			return errors.New("point lot has a negative accounting counter")
		}
		var err error
		accounted, err = checkedAdd(accounted, value)
		if err != nil {
			return err
		}
	}
	if lot.InitialMicro < 0 || accounted != lot.InitialMicro {
		return errors.New("point lot accounting does not conserve the original amount")
	}
	return nil
}
